const stateNames = {
    AN: "Andaman and Nicobar Islands",
    AP: "Andhra Pradesh",
    AR: "Arunachal Pradesh",
    AS: "Assam",
    BR: "Bihar",
    CH: "Chandigarh",
    CT: "Chhattisgarh",
    DN: "Dadra and Nagar Haveli",
    DD: "Daman and Diu",
    DL: "Delhi",
    GA: "Goa",
    GJ: "Gujarat",
    HR: "Haryana",
    HP: "Himachal Pradesh",
    JK: "Jammu and Kashmir",
    JH: "Jharkhand",
    KA: "Karnataka",
    KL: "Kerala",
    LH: "Ladakh",
    LD: "Lakshadweep",
    MP: "Madhya Pradesh",
    MH: "Maharashtra",
    MN: "Manipur",
    ML: "Meghalaya",
    MZ: "Mizoram",
    NL: "Nagaland",
    OR: "Odisha",
    PY: "Puducherry",
    PB: "Punjab",
    RJ: "Rajasthan",
    SK: "Sikkim",
    TN: "Tamil Nadu",
    TG: "Telangana",
    TR: "Tripura",
    UP: "Uttar Pradesh",
    UT: "Uttarakhand",
    WB: "West Bengal"
};

const stateCodes = {
    AN: 1,
    AP: 2,
    AR: 3,
    AS: 4,
    BR: 5,
    CH: 6,
    CT: 7,
    DN: 8,
    DD: 9,
    DL: 10,
    GA: 11,
    GJ: 12,
    HR: 13,
    HP: 14,
    JK: 15,
    JH: 16,
    KA: 17,
    KL: 18,
    LH: 19,
    LD: 20,
    MP: 21,
    MH: 22,
    MN: 23,
    ML: 24,
    MZ: 25,
    NL: 26,
    OR: 27,
    PY: 28,
    PB: 29,
    RJ: 30,
    SK: 31,
    TN: 32,
    TG: 33,
    TR: 34,
    UP: 35,
    UT: 36,
    WB: 37
};

const stateNumbers = {
    1:"AN",
    2: "AP",
    3: "AR",
    4: "AS",
    5: "BR",
    6: "CH",
    7: "CT",
    8: "DN",
    9: "DD",
    10: "DL",
    11: "GA",
    12: "GJ",
    13: "HR",
    14: "HP",
    15: "JK",
    16: "JH",
    17: "KA",
    18: "KL",
    19: "LH",
    20: "LD",
    21: "MP",
    22: "MH",
    23: "MN",
    24: "ML",
    25: "MZ",
    26: "NL",
    27: "OR",
    28: "PY",
    29: "PB",
    30: "RJ",
    31: "SK",
    32: "TN",
    33: "TG",
    34: "TR",
    35: "UP",
    36: "UT",
    37: "WB"

}

module.exports = {
    stateNames,
    stateCodes,
    stateNumbers
}
