const stateNames = {
    AN: "Andaman and Nicobar Islands",
    AP: "Andhra Pradesh",
    AR: "Arunachal Pradesh",
    AS: "Assam",
    BR: "Bihar",
    CH: "Chandigarh",
    CT: "Chhattisgarh",
    DN: "Dadra and Nagar Haveli",
    DD: "Daman and Diu",
    DL: "Delhi",
    GA: "Goa",
    GJ: "Gujarat",
    HR: "Haryana",
    HP: "Himachal Pradesh",
    JK: "Jammu and Kashmir",
    JH: "Jharkhand",
    KA: "Karnataka",
    KL: "Kerala",
    LH: "Ladakh",
    LD: "Lakshadweep",
    MP: "Madhya Pradesh",
    MH: "Maharashtra",
    MN: "Manipur",
    ML: "Meghalaya",
    MZ: "Mizoram",
    NL: "Nagaland",
    OR: "Odisha",
    PY: "Puducherry",
    PB: "Punjab",
    RJ: "Rajasthan",
    SK: "Sikkim",
    TN: "Tamil Nadu",
    TG: "Telangana",
    TR: "Tripura",
    UP: "Uttar Pradesh",
    UT: "Uttarakhand",
    WB: "West Bengal"
};

const stateCodes = {
    AN: 1,
    AP: 2,
    AR: 3,
    AS: 4,
    BR: 5,
    CH: 6,
    CT: 7,
    DN: 8,
    DD: 9,
    DL: 10,
    GA: 11,
    GJ: 12,
    HR: 13,
    HP: 14,
    JK: 15,
    JH: 16,
    KA: 17,
    KL: 18,
    LH: 19,
    LD: 20,
    MP: 21,
    MH: 22,
    MN: 23,
    ML: 24,
    MZ: 25,
    NL: 26,
    OR: 27,
    PY: 28,
    PB: 29,
    RJ: 30,
    SK: 31,
    TN: 32,
    TG: 33,
    TR: 34,
    UP: 35,
    UT: 36,
    WB: 37
};

module.exports = {
    stateNames,
    stateCodes
}
